# Generated by Django 5.1 on 2024-08-15 01:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Block',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('block_id', models.IntegerField(unique=True)),
                ('block_hash', models.CharField(max_length=100, unique=True)),
                ('parentHash', models.CharField(max_length=100)),
                ('stateRoot', models.CharField(max_length=100)),
                ('extrinsicsRoot', models.CharField(max_length=100)),
                ('timestamp', models.DateTimeField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Call',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('call_index', models.CharField(max_length=12, unique=True)),
                ('call_function', models.CharField(max_length=30, null=True)),
                ('call_module', models.CharField(max_length=30, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Extrinsic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('netuid', models.IntegerField(null=True)),
                ('hash', models.CharField(max_length=64, unique=True)),
                ('address', models.CharField(max_length=255, null=True)),
                ('idx', models.CharField(max_length=12, null=True)),
                ('signature', models.JSONField(null=True)),
                ('tip', models.IntegerField(null=True)),
                ('nonce', models.IntegerField(null=True)),
                ('era', models.CharField(max_length=10, null=True)),
                ('call_args', models.JSONField(null=True)),
                ('result', models.CharField(max_length=20, null=True)),
                ('events', models.JSONField(null=True)),
                ('block', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='extrinsics', to='myapp.block', to_field='block_id')),
                ('call_index', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='extrinsics', to='myapp.call', to_field='call_index')),
            ],
        ),
    ]
